uploads = []

[[generated]]
id = "-RnK0b1uTWIvjEliYnyz5"
uri = "file://assets/icon.png"
type = "image"
title = "resqride app icon"

[[generated]]
id = "jFPF6U0EgNzLf9KSixV-Q"
uri = "file://assets/splash.png"
type = "image"
title = "resqride splash screen"

[[generated]]
id = "w_dGhNCFCoc-BNu8exUi-"
uri = "file://assets/adaptive-icon.png"
type = "image"
title = "resqride adaptive icon"

[[outputs]]
id = "rzNACwEkupQemUuqwIcmK"
uri = "file://attached_assets/resqride_logo_nobg.png"
type = "image"
title = "ResqRide Logo - No Background"
