// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/provider-profiles/Business.tsx": () => import("../components/mockups/provider-profiles/Business.tsx"),
  "./components/mockups/provider-profiles/Independent.tsx": () => import("../components/mockups/provider-profiles/Independent.tsx"),
  "./components/mockups/chrome-screens/Dashboard.tsx": () => import("../components/mockups/chrome-screens/Dashboard.tsx"),
  "./components/mockups/chrome-screens/SignIn.tsx": () => import("../components/mockups/chrome-screens/SignIn.tsx"),
  "./components/mockups/chrome-screens/Welcome.tsx": () => import("../components/mockups/chrome-screens/Welcome.tsx")
};
