import type { ServiceRequest } from "@/context/AppContext";

const MIKE_PROVIDER = {
  id: "p1",
  name: "Mike's Towing",
  phone: "+1 555-0101",
  email: "mike@towing.com",
  rating: 4.8,
  reviewCount: 156,
  vehicleType: "tow_truck" as const,
  vehicleMake: "Ford",
  vehicleModel: "F-550",
  licensePlate: "TOW-123",
  servicesOffered: ["tow" as const, "flat_tire" as const, "jump_start" as const, "lockout" as const],
  isAvailable: true,
  providerType: "shop" as const,
  verificationStatus: "verified" as const,
};

const ROAD_RESCUE_PROVIDER = {
  id: "p3",
  name: "Road Rescue",
  phone: "+1 555-0103",
  email: "help@roadrescue.com",
  rating: 4.9,
  reviewCount: 234,
  vehicleType: "pickup" as const,
  vehicleMake: "Chevrolet",
  vehicleModel: "Silverado",
  licensePlate: "RES-789",
  servicesOffered: ["flat_tire" as const, "jump_start" as const, "fuel" as const, "other" as const],
  isAvailable: true,
  providerType: "independent" as const,
  verificationStatus: "verified" as const,
};

export const mockHistory: ServiceRequest[] = [
  {
    id: "h1",
    serviceType: "flat_tire",
    location: { address: "123 Main St, San Francisco, CA", latitude: 37.78, longitude: -122.41 },
    notes: "",
    status: "completed",
    estimatedCost: 72,
    createdAt: new Date(Date.now() - 86400000 * 2),
    timeSaved: 35,
    receiptNumber: "SM-ABC123",
    provider: MIKE_PROVIDER,
  },
  {
    id: "h2",
    serviceType: "jump_start",
    location: { address: "456 Oak Ave, Oakland, CA", latitude: 37.80, longitude: -122.27 },
    notes: "",
    status: "completed",
    estimatedCost: 47,
    createdAt: new Date(Date.now() - 86400000 * 7),
    timeSaved: 22,
    receiptNumber: "SM-DEF456",
    provider: {
      id: "p2",
      name: "Quick Fix Auto",
      phone: "+1 555-0102",
      email: "quick@fixauto.com",
      rating: 4.6,
      reviewCount: 89,
      vehicleType: "service_van",
      vehicleMake: "Mercedes",
      vehicleModel: "Sprinter",
      licensePlate: "FIX-456",
      servicesOffered: ["flat_tire", "jump_start", "fuel", "lockout"],
      isAvailable: true,
      providerType: "shop",
      verificationStatus: "verified",
    },
  },
  {
    id: "h3",
    serviceType: "fuel",
    location: { address: "789 Pine Blvd, Berkeley, CA", latitude: 37.87, longitude: -122.26 },
    notes: "Out of gas on highway",
    status: "completed",
    estimatedCost: 38,
    createdAt: new Date(Date.now() - 86400000 * 14),
    timeSaved: 40,
    receiptNumber: "SM-GHI789",
    provider: ROAD_RESCUE_PROVIDER,
  },
  {
    id: "h4",
    serviceType: "lockout",
    location: { address: "321 Market St, San Francisco, CA", latitude: 37.79, longitude: -122.40 },
    notes: "Keys locked inside car",
    status: "completed",
    estimatedCost: 55,
    createdAt: new Date(Date.now() - 86400000 * 30),
    timeSaved: 28,
    receiptNumber: "SM-JKL012",
    provider: {
      id: "p5",
      name: "Carlos H.",
      phone: "+1 555-0105",
      email: "carlos@helpers.com",
      rating: 4.7,
      reviewCount: 42,
      vehicleType: "pickup",
      vehicleMake: "Toyota",
      vehicleModel: "Tacoma",
      licensePlate: "HLP-555",
      servicesOffered: ["flat_tire", "jump_start", "fuel"],
      isAvailable: true,
      providerType: "independent",
      verificationStatus: "verified",
    },
  },
  {
    id: "h5",
    serviceType: "jump_start",
    location: { address: "550 Geary St, San Francisco, CA", latitude: 37.79, longitude: -122.41 },
    notes: "Dead battery after concert",
    status: "completed",
    estimatedCost: 47,
    createdAt: new Date(Date.now() - 86400000 * 45),
    timeSaved: 20,
    receiptNumber: "SM-MNO345",
    provider: MIKE_PROVIDER,
  },
  {
    id: "h6",
    serviceType: "lockout",
    location: { address: "1200 Van Ness Ave, San Francisco, CA", latitude: 37.79, longitude: -122.42 },
    notes: "",
    status: "completed",
    estimatedCost: 55,
    createdAt: new Date(Date.now() - 86400000 * 60),
    timeSaved: 30,
    receiptNumber: "SM-PQR678",
    provider: MIKE_PROVIDER,
  },
  {
    id: "h7",
    serviceType: "flat_tire",
    location: { address: "2100 Mission St, San Francisco, CA", latitude: 37.76, longitude: -122.42 },
    notes: "Nail in tire",
    status: "completed",
    estimatedCost: 77,
    createdAt: new Date(Date.now() - 86400000 * 75),
    timeSaved: 45,
    receiptNumber: "SM-STU901",
    provider: ROAD_RESCUE_PROVIDER,
  },
  {
    id: "h8",
    serviceType: "fuel",
    location: { address: "3500 24th St, San Francisco, CA", latitude: 37.75, longitude: -122.42 },
    notes: "Ran out near home",
    status: "completed",
    estimatedCost: 36,
    createdAt: new Date(Date.now() - 86400000 * 90),
    timeSaved: 35,
    receiptNumber: "SM-VWX234",
    provider: ROAD_RESCUE_PROVIDER,
  },
  {
    id: "h9",
    serviceType: "tow",
    location: { address: "Embarcadero, San Francisco, CA", latitude: 37.80, longitude: -122.40 },
    notes: "Engine trouble",
    status: "completed",
    estimatedCost: 128,
    createdAt: new Date(Date.now() - 86400000 * 100),
    timeSaved: 50,
    receiptNumber: "SM-YZA567",
    provider: MIKE_PROVIDER,
  },
];
