export const VEHICLE_MAKES_MODELS: Record<string, string[]> = {
  "Acura": ["ILX", "Integra", "MDX", "RDX", "TLX", "NSX"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale"],
  "Audi": ["A3", "A4", "A5", "A6", "A7", "A8", "e-tron", "Q3", "Q5", "Q7", "Q8", "RS5", "RS7", "S4", "S5", "TT"],
  "BMW": ["2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "8 Series", "i4", "i5", "i7", "iX", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "M3", "M4", "M5"],
  "Buick": ["Enclave", "Encore", "Encore GX", "Envision", "Envista"],
  "Cadillac": ["CT4", "CT5", "Escalade", "Escalade ESV", "Lyriq", "XT4", "XT5", "XT6"],
  "Chevrolet": ["Blazer", "Bolt EUV", "Bolt EV", "Camaro", "Colorado", "Corvette", "Equinox", "Malibu", "Silverado 1500", "Silverado 2500HD", "Suburban", "Tahoe", "Trailblazer", "Traverse", "Trax"],
  "Chrysler": ["300", "Pacifica", "Voyager"],
  "Dodge": ["Challenger", "Charger", "Durango", "Hornet"],
  "Fiat": ["500X"],
  "Ford": ["Bronco", "Bronco Sport", "Edge", "Escape", "Expedition", "Explorer", "F-150", "F-250", "F-350", "Maverick", "Mustang", "Mustang Mach-E", "Ranger", "Transit"],
  "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "GMC": ["Acadia", "Canyon", "Hummer EV", "Sierra 1500", "Sierra 2500HD", "Terrain", "Yukon", "Yukon XL"],
  "Honda": ["Accord", "Civic", "CR-V", "HR-V", "Odyssey", "Passport", "Pilot", "Prologue", "Ridgeline"],
  "Hyundai": ["Elantra", "Ioniq 5", "Ioniq 6", "Kona", "Palisade", "Santa Cruz", "Santa Fe", "Sonata", "Tucson", "Venue"],
  "Infiniti": ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  "Jaguar": ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XF"],
  "Jeep": ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Grand Cherokee L", "Grand Wagoneer", "Renegade", "Wagoneer", "Wrangler"],
  "Kia": ["Carnival", "EV6", "EV9", "Forte", "K5", "Niro", "Rio", "Seltos", "Sorento", "Soul", "Sportage", "Stinger", "Telluride"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  "Lexus": ["ES", "GX", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "RZ", "TX", "UX"],
  "Lincoln": ["Aviator", "Corsair", "Nautilus", "Navigator"],
  "Maserati": ["Ghibli", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  "Mazda": ["CX-30", "CX-5", "CX-50", "CX-70", "CX-90", "Mazda3", "MX-5 Miata", "MX-30"],
  "Mercedes-Benz": ["A-Class", "C-Class", "CLA", "CLE", "E-Class", "EQB", "EQE", "EQS", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "S-Class", "SL"],
  "Mini": ["Clubman", "Convertible", "Countryman", "Hardtop 2 Door", "Hardtop 4 Door"],
  "Mitsubishi": ["Eclipse Cross", "Mirage", "Outlander", "Outlander Sport"],
  "Nissan": ["Altima", "Ariya", "Frontier", "Kicks", "Leaf", "Maxima", "Murano", "Pathfinder", "Rogue", "Sentra", "Titan", "Versa", "Z"],
  "Porsche": ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  "Ram": ["1500", "2500", "3500", "ProMaster"],
  "Rivian": ["R1S", "R1T"],
  "Subaru": ["Ascent", "BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "Solterra", "WRX"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"],
  "Toyota": ["4Runner", "bZ4X", "Camry", "Corolla", "Corolla Cross", "Crown", "GR86", "GR Supra", "Grand Highlander", "Highlander", "Prius", "RAV4", "Sequoia", "Sienna", "Tacoma", "Tundra", "Venza"],
  "Volkswagen": ["Atlas", "Atlas Cross Sport", "Golf GTI", "Golf R", "ID.4", "ID.Buzz", "Jetta", "Taos", "Tiguan"],
  "Volvo": ["C40 Recharge", "S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
};

export const VEHICLE_MAKES = Object.keys(VEHICLE_MAKES_MODELS).sort();

export const TOW_TRUCK_MAKES_MODELS: Record<string, string[]> = {
  "Chevrolet": [
    "Silverado 4500HD",
    "Silverado 5500HD",
    "Silverado 6500HD",
  ],
  "Ford": [
    "F-450 Super Duty",
    "F-550 Super Duty",
    "F-650 Super Duty",
    "F-750 Super Duty",
  ],
  "Freightliner": [
    "M2 106",
    "M2 106 Plus",
    "108SD",
    "Cascadia 126",
  ],
  "GMC": [
    "Sierra 4500HD",
    "Sierra 5500HD",
  ],
  "Hino": [
    "195",
    "195H",
    "258",
    "258ALP",
    "268",
    "268A",
    "338",
  ],
  "International": [
    "CV515",
    "HX520",
    "HX615",
    "MV607",
    "MV607 SBA",
  ],
  "Isuzu": [
    "NPR-HD",
    "NQR",
    "NRR",
    "FTR",
    "FVR",
  ],
  "Kenworth": [
    "T270",
    "T370",
    "T470",
    "T680",
    "W900",
  ],
  "Mack": [
    "Anthem",
    "Granite",
    "Pinnacle",
    "TerraPro",
  ],
  "Peterbilt": [
    "320",
    "337",
    "348",
    "365",
    "386",
    "389",
  ],
  "RAM": [
    "3500 Tradesman",
    "4500 Tradesman",
    "5500 Tradesman",
  ],
  "Sterling": [
    "A-Line",
    "L-Line 7500",
    "L-Line 8500",
    "L-Line 9500",
  ],
  "Volvo Trucks": [
    "VNL 300",
    "VNL 400",
    "VNL 760",
    "VNL 860",
    "VHD 300",
  ],
  "Western Star": [
    "4700",
    "4900",
    "47X",
    "49X",
    "57X",
  ],
};

export const TOW_TRUCK_MAKES = Object.keys(TOW_TRUCK_MAKES_MODELS).sort();

export const TOW_TRUCK_CLASSES: { label: string; description: string }[] = [
  { label: "Light-Duty Wrecker", description: "Passenger cars, small trucks (up to 10,000 lbs)" },
  { label: "Medium-Duty Wrecker", description: "Vans, box trucks, medium vehicles (up to 26,000 lbs)" },
  { label: "Heavy-Duty Wrecker", description: "Semi-trucks, buses, large vehicles (26,000+ lbs)" },
  { label: "Flatbed / Rollback", description: "Transports on a flat platform, all vehicle types" },
  { label: "Integrated / Repo", description: "Wheel-lift integrated, repo and tight-space towing" },
  { label: "Rotator", description: "360° boom, complex recoveries and heavy rescues" },
];
